{
 "title": "NSB Single Node",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "scenario",
    "label": "scenario",
    "query": {
     "query": "label_values({instance=~\"$instance\"},scenario)"
    }
   },
   {
    "name": "vendor",
    "label": "Vendor",
    "query": {
     "query": "label_values({instance=~\"$instance\"},vendor)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values({instance=~\"$instance\"},node)"
    }
   },
   {
    "name": "activity",
    "label": "activity",
    "query": {
     "query": "label_values({instance=~\"$instance\",scenario=~\"$scenario\"},activity)"
    }
   },
   {
    "name": "k",
    "label": "K",
    "query": {
     "query": "label_values({instance=~\"$instance\"},k)"
    }
   },
   {
    "name": "op",
    "label": "Op",
    "query": {
     "query": "label_values({instance=~\"$instance\",scenario=~\"$scenario\"},op)"
    }
   },
   {
    "name": "dataset",
    "label": "Dataset",
    "query": {
     "query": "label_values({instance=~\"$instance\"},dataset)"
    }
   },
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "label_values({instance=~\"$instance\"},target)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Vendor:$vendor Instance:$instance Scenario:$scenario Node:$node Activity:$activity K:$k Op:$op ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  { "title": "Relevance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Recall",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "{__name__=~\"recall.*\",instance=~\"$instance\",job=\"nosqlbench\",scenario=~\"$scenario\",activity=~\"$activity\",k=~\"$k\",target=~\"$target\"}"
    },
    {
     "expr": "{__name__=~\"recall_100_w.*\",instance=~\"$instance\",job=\"nosqlbench\",scenario=~\"$scenario\",activity=~\"$activity\",k=~\"$k\",target=~\"$target\"}"
    }
   ]
  },
  {
   "title": "Precision",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "{__name__=~\"precision.*\",instance=~\"$instance\",job=\"nosqlbench\",scenario=~\"$scenario\",activity=~\"$activity\",k=~\"$k\",target=~\"$target\"}"
    }
   ]
  },
  { "title": "NB5 Diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Cycles V:$vendor S:$scenario A:$activity",
   "type": "timeseries",
   "description": "This view shows the current cycle progress in terms of cycles values dispensed to threads and a count of those which have been fully processed.\n\n__Dispatched cycles__ are those which have been allocated to activity threads to process. __Retired cycles__ are those which have not been retired or completed. \n\nThe difference between the two represents work which is subscribed by activity threads but not yet complete.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cycles_servicetime_total{job=\"nosqlbench\",instance=~\"$instance\",scenario=~\"$scenario\",activity=~\"$activity\",node=~\"$node\",target=~\"$target\"}",
     "legendFormat": "{{target}} {{scenario}} {{node}} retired"
    },
    {
     "expr": "cycle{job=\"nosqlbench\",instance=~\"$instance\",scenario=~\"$scenario\",activity=~\"$activity\",node=~\"$node\",target=~\"$target\"}",
     "legendFormat": "{{target}}-{{node}} dispatched"
    }
   ]
  },
  {
   "title": "Ops V:$vendor S:$scenario A:$activity",
   "type": "timeseries",
   "description": "These two metrics show the 1-minute averaged ops per second for all ops (successes and errors) and succesful ops (no errors during execution) separately.\\n\\nWhen there are no errors, these metrics should be the same. When there are errors, there will be a difference. In that case, you can look at the error metrics to learn more about what is happening.\n\nBy comparing these two metrics for any activity, you have a quick first-glance sanity check that your tests are configured properly and\\nthat there are no serious configuration or resource issues. In addition, this is the primary throughput metric.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg_over_time(result_1mRate{job=\"nosqlbench\", instance=~\"$instance\", scenario=~\"$scenario\", activity=~\"$activity\",target=~\"$target\"}[1m])",
     "legendFormat": "{{target}}-{{dataset}}-{{scenario}}-{{activity}}-{{node}}-ALL"
    },
    {
     "expr": "avg_over_time(result_success_1mRate{job=\"nosqlbench\", instance=~\"$instance\", scenario=~\"$scenario\", activity=~\"$activity\",target=~\"$target\"}[1m])",
     "legendFormat": "{{target}}-{{dataset}}-{{scenario}}-{{activity}}-{{node}}-OK"
    }
   ]
  },
  {
   "title": "Tries V:$vendor S:$scenario A:$activity",
   "type": "timeseries",
   "description": "The tries distribution is an HDR histogram which represents how many times an operation was submitted. In a well balanced system, tries should be 1 across the board.\n\nEvery operation which is executed within NoSQLBench should have a `tries` metric. For example, with CQL, the number of times an operation is submitted before it is succesful is ideally 1. If you are overloading your target system, thus forcing resource contention, you may see operations timeout.\n\n\nBy default, NoSQLBench will try up to 10 times to submit operations before giving up and throwing an error for an operation.\n\nThe tries metric can be used as a low-noise indicator of system saturation. For example, if you are running a system marginally beyond its capacity, the tries for operations will go above 1 at the higher percentiles such as P99. If you increase the load even further, more retries will be needed and less work will be completed, thus showing higher retries at even lower percentiles, like P95, for example.\n\nAs such, you can use the tries metric as an indicator of relative saturation.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tries_bucket{job=\"nosqlbench\",instance=~\"$instance\",scenario=~\"$scenario\",activity=~\"$activity\",node=~\"$node\",target=~\"$target\"}",
     "legendFormat": "{{target}}-{{scenario}}-{{node}}-{{activity}}-{{le}}"
    }
   ]
  },
  {
   "title": "Errors V:$vendor S:$scenario A:$activity",
   "type": "timeseries",
   "description": "When an exception is caught and counted in a scenario, a specially named metric is emited which includes a simplified name of the error type.\n\nEach of these metrics is created as needed in the NoSQLBench runtime.\n\nThese metrics are formated with a name pattern of `errorcounts.NAME` where NAME is the simple name of the exception class which was caught during the operation. For example, For an activity named `foo``, you would expect an exception named `FooTimeoutException` to be shown with a metric name of ... `foo.errorcounts.FooTimeoutException`",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=~\"errors_.*_total\",job=\"nosqlbench\",activity=~\"$activity\",instance=~\"$instance\",scenario=~\"$scenario\",target=~\"$target\"}",
     "legendFormat": "{{target}}-{{__name__}}"
    },
    {
     "expr": "{__name__=~\"errors_ALL_total\", job=\"nosqlbench\", activity=~\"$activity\", instance=~\"$instance\", scenario=~\"$scenario\",target=~\"$target\"}",
     "legendFormat": "{{target}}-{{node}}-{{__name__}}"
    }
   ]
  },
  {
   "title": "OPS & THREADS [$scenario-$activity-$target]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "ops_pending{instance=~\"$instance\",scenario=~\"$scenario\",activity=~\"$activity\"}",
     "legendFormat": "{{workload}}-{{scenario}}-{{activity}}-{{target}}-{{dataset}}-{{dimensions}} PENDING OPS"
    },
    {
     "expr": "ops_complete{instance=~\"$instance\",scenario=~\"$scenario\",activity=~\"$activity\"}",
     "legendFormat": "{{workload}}-{{scenario}}-{{activity}}-{{target}}-{{dataset}}-{{dimensions}} COMPLETE OPS"
    },
    {
     "expr": "ops_active{instance=~\"$instance\",scenario=~\"$scenario\",activity=~\"$activity\"}",
     "legendFormat": "{{workload}}-{{scenario}}-{{activity}}-{{target}}-{{dataset}}-{{dimensions}} ACTIVE OPS"
    },
    {
     "expr": "threads{workload=~\"$workload\", activity=~\"$activity\", instance=~\"$instance\", session=~\"$session\", scenario=~\"$scenario\", target=~\"$target\", container=~\"$container\"}",
     "legendFormat": "{{workload}}-{{scenario}}-{{activity}}-{{target}}-{{dataset}}-{{dimensions}} THREADS"
    }
   ]
  },
  {
   "title": "SvcTime V:$vendor S:$scenario A:$activity",
   "type": "timeseries",
   "description": "The service time distribution is an HDR histogram that represents the time elapsed from when an operation is submitted for execution to when its result has been received.\n\nFrom the vantage point of the NoSQLBench runtime, this is a client-side metric. Thus, the service time captures the processing time that an application would see, including driver logic, wire time (transport), and server-side processing.\n\nThis metric does not include the waittime or the responsetime metrics. These metrics are only meaningful (and provided) when a `cyclerate=` is provided to an activity. When computing the responsetime metric, the servicetime is added to the waittime for a given operation.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "result_success_bucket{job=\"nosqlbench\",instance=~\"$instance\",scenario=~\"$scenario\",activity=~\"$activity\",node=~\"$node\",target=~\"$target\"}",
     "legendFormat": "{{target}}-{{scenario}}-{{activity}}-{{dataset}}-{{le}}"
    },
    {
     "expr": "result_success_bucket{job=\"nosqlbench\",instance=~\"$instance\",scenario=~\"$scenario\",activity=~\"$activity\",node=~\"$node\",target=~\"$target\",le=\"0.95\"}",
     "legendFormat": "P95-{{target}}-{{scenario}}-{{activity}}-{{dataset}}-{{le}}"
    },
    {
     "expr": "result_success_bucket{job=\"nosqlbench\",instance=~\"$instance\",scenario=~\"$scenario\",activity=~\"$activity\",node=~\"$node\",target=~\"$target\",le=\"0.99\"}",
     "legendFormat": "P99-{{target}}-{{scenario}}-{{activity}}-{{dataset}}-{{le}}"
    }
   ]
  },
  {
   "title": "SvcTime/1m V:$vendor S:$scenario A:$activity",
   "type": "timeseries",
   "description": "The service time distribution is an HDR histogram that represents the time elapsed from when an operation is submitted for execution to when its result has been received.\n\nFrom the vantage point of the NoSQLBench runtime, this is a client-side metric. Thus, the service time captures the processing time that an application would see, including driver logic, wire time (transport), and server-side processing.\n\nThis metric does not include the waittime or the responsetime metrics. These metrics are only meaningful (and provided) when a `cyclerate=` is provided to an activity. When computing the responsetime metric, the servicetime is added to the waittime for a given operation.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "result_success_bucket{job=\"nosqlbench\",instance=~\"$instance\",scenario=~\"$scenario\",activity=~\"$activity\",node=~\"$node\",target=~\"$target\"}",
     "legendFormat": "{{target}}-{{scenario}}-{{activity}}-{{dataset}}-{{le}}"
    }
   ]
  },
  {
   "title": "Progress V:$vendor S:$scenario A:$activity",
   "type": "timeseries",
   "description": "This panel shows the number of cycles remaining, pending, and complete for a given activity",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "ops_pending{job=\"nosqlbench\",instance=~\"$instance\",scenario=~\"$scenario\",activity=~\"$activity\",node=~\"$node\",target=~\"$target\"}",
     "legendFormat": "{{target}}-{{node}}-pending"
    },
    {
     "expr": "ops_active{job=\"nosqlbench\",instance=~\"$instance\",scenario=~\"$scenario\",activity=~\"$activity\",node=~\"$node\",target=~\"$target\"}",
     "legendFormat": "{{target}}-{{node}}-active"
    },
    {
     "expr": "ops_complete{job=\"nosqlbench\",instance=~\"$instance\",scenario=~\"$scenario\",activity=~\"$activity\",node=~\"$node\",target=~\"$target\"}",
     "legendFormat": "{{target}}-{{node}}-complete"
    }
   ]
  },
  {
   "title": "Specific Ops [$op]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "op",
   "collapsed": true,
   "panels": [
    {
     "title": "SUCCESSES for $op [$scenario $activity]",
     "type": "timeseries",
     "description": "This is a view of successful operations for a specific op:\n- op: $op\n- scenario: $scenario\n- activity: $activity",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "{__name__=~\"successfor_.*_bucket\",job=\"nosqlbench\", instance=~\"$instance\", scenario=~\"$scenario\", activity=~\"$activity\", op=~\"$op\"}",
       "legendFormat": "{{node}}-{{op}}-success-{{le}}"
      },
      {
       "expr": "{__name__=~\"successfor_.*1mRate\",job=\"nosqlbench\", instance=~\"$instance\", scenario=~\"$scenario\", activity=~\"$activity\", op=~\"$op\"}",
       "legendFormat": "{{op}}-1mrate"
      }
     ]
    },
    {
     "title": "ERRORS for $op [$scenario $activity]",
     "type": "timeseries",
     "description": "These two metrics show the 1-minute averaged ops per second for all ops (successes and errors) and succesful ops (no errors during execution) separately.\\n\\nWhen there are no errors, these metrics should be the same. When there are errors, there will be a difference. In that case, you can look at the error metrics to learn more about what is happening.\n\nBy comparing these two metrics for any activity, you have a quick first-glance sanity check that your tests are configured properly and\\nthat there are no serious configuration or resource issues. In addition, this is the primary throughput metric.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "{__name__=~\"errorsfor_.*_bucket\",job=\"nosqlbench\", instance=~\"$instance\", scenario=~\"$scenario\", activity=~\"$activity\",op=~\"$op\"}",
       "legendFormat": "{{node}}-{{op}}-errors-{{le}}"
      },
      {
       "expr": "{__name__=~\"errorsfor_.*1mRate\",job=\"nosqlbench\", instance=~\"$instance\", scenario=~\"$scenario\", activity=~\"$activity\", op=~\"$op\"}",
       "legendFormat": "{{op}}-1m error rate"
      }
     ]
    }
   ]
  }
 ]
}